### ISSUE TITLE
Exception processing input containing extension methods

### ISSUE THREAD

**Issue by davidmatson** [docascode/ECMA2Yaml#7]
(Previously communicated offline; this issue may already be fixed now.)

When running ECMA2Yaml.exe with an input file containing extension methods, I get the following exception:
```
[2017-10-31 10:51:08]Loading ECMAXML files...
[2017-10-31 10:51:08]Building loaded files...
[2017-10-31 10:51:08]System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ECMA2Yaml.Models.ECMAStore.BuildExtensionMethods()
   at ECMA2Yaml.Models.ECMAStore.Build()
   at ECMA2Yaml.Program.LoadAndConvert(CommandLineOptions opt)
   at ECMA2Yaml.Program.Main(String[] args)
```

From a local repro, the problem is in this line of code:
```
List<string> typeMonikers = t.Metadata[OPSMetadata.Monikers] as List<string>;
```

In this case, the Metadata dictionary is empty.

**Comment by TianqiZhang** [comment]
This issue is fixed by commit 2d1102e6183bb394cfa96777047e10ab8b2a1728
